/*******************************************************************************
* File Name: cyfitter_sysint_cfg.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_CFG_H
#define INCLUDED_CYFITTER_SYSINT_CFG_H

#include "sysint/cy_sysint.h"

/* ARM CM0+ */
#if (((__CORTEX_M == 0) && (CY_CORE_ID == 0)))
    #define tty_rx_int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t tty_rx_int_cfg;

#endif /* ((__CORTEX_M == 0) && (CY_CORE_ID == 0)) */

/* ARM CM4 */
#if (((__CORTEX_M == 4) && (CY_CORE_ID == 0)))
    #define tty_rx_int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t tty_rx_int_cfg;

    #define I2C_SCB_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t I2C_SCB_IRQ_cfg;

    #define Button1_Int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t Button1_Int_cfg;

    #define Button2_Int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t Button2_Int_cfg;

    #define Button3_Int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t Button3_Int_cfg;

    #define Button4_Int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t Button4_Int_cfg;

    #define Button5_Int__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t Button5_Int_cfg;

    #define ADC_IRQ__INTC_ASSIGNED 1u
    extern const cy_stc_sysint_t ADC_IRQ_cfg;

#endif /* ((__CORTEX_M == 4) && (CY_CORE_ID == 0)) */


#endif /* INCLUDED_CYFITTER_SYSINT_CFG_H */
