/*******************************************************************************
* File Name: cyfitter_sysint_cfg.c
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_sysint.h"
#include "cyfitter_sysint_cfg.h"

/* ARM CM0+ */
#if (((__CORTEX_M == 0) && (CY_CORE_ID == 0)))

    /* tty_rx_int */
    const cy_stc_sysint_t tty_rx_int_cfg = {
        .intrSrc = (IRQn_Type)tty_rx_int__INTC_CORTEXM0P_MUX,
        .cm0pSrc = (cy_en_intr_t)tty_rx_int__INTC_NUMBER,
        .intrPriority = tty_rx_int__INTC_CORTEXM0P_PRIORITY
    };

#endif /* ((__CORTEX_M == 0) && (CY_CORE_ID == 0)) */

/* ARM CM4 */
#if (((__CORTEX_M == 4) && (CY_CORE_ID == 0)))

    /* tty_rx_int */
    const cy_stc_sysint_t tty_rx_int_cfg = {
        .intrSrc = (IRQn_Type)tty_rx_int__INTC_NUMBER,
        .intrPriority = tty_rx_int__INTC_CORTEXM4_PRIORITY
    };

    /* I2C_SCB_IRQ */
    const cy_stc_sysint_t I2C_SCB_IRQ_cfg = {
        .intrSrc = (IRQn_Type)I2C_SCB_IRQ__INTC_NUMBER,
        .intrPriority = I2C_SCB_IRQ__INTC_CORTEXM4_PRIORITY
    };

    /* Button1_Int */
    const cy_stc_sysint_t Button1_Int_cfg = {
        .intrSrc = (IRQn_Type)Button1_Int__INTC_NUMBER,
        .intrPriority = Button1_Int__INTC_CORTEXM4_PRIORITY
    };

    /* Button2_Int */
    const cy_stc_sysint_t Button2_Int_cfg = {
        .intrSrc = (IRQn_Type)Button2_Int__INTC_NUMBER,
        .intrPriority = Button2_Int__INTC_CORTEXM4_PRIORITY
    };

    /* Button3_Int */
    const cy_stc_sysint_t Button3_Int_cfg = {
        .intrSrc = (IRQn_Type)Button3_Int__INTC_NUMBER,
        .intrPriority = Button3_Int__INTC_CORTEXM4_PRIORITY
    };

    /* Button4_Int */
    const cy_stc_sysint_t Button4_Int_cfg = {
        .intrSrc = (IRQn_Type)Button4_Int__INTC_NUMBER,
        .intrPriority = Button4_Int__INTC_CORTEXM4_PRIORITY
    };

    /* Button5_Int */
    const cy_stc_sysint_t Button5_Int_cfg = {
        .intrSrc = (IRQn_Type)Button5_Int__INTC_NUMBER,
        .intrPriority = Button5_Int__INTC_CORTEXM4_PRIORITY
    };

    /* ADC_IRQ */
    const cy_stc_sysint_t ADC_IRQ_cfg = {
        .intrSrc = (IRQn_Type)ADC_IRQ__INTC_NUMBER,
        .intrPriority = ADC_IRQ__INTC_CORTEXM4_PRIORITY
    };

#endif /* ((__CORTEX_M == 4) && (CY_CORE_ID == 0)) */

