/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* ADC_IRQ */
#define ADC_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define ADC_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define ADC_IRQ__INTC_NUMBER 138u
#define ADC_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define ADC_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define ADC_IRQ_INTC_NUMBER 138u

/* tty_rx_int */
#define tty_rx_int__INTC_CORTEXM0P_ASSIGNED 1
#define tty_rx_int__INTC_CORTEXM0P_MUX 8u
#define tty_rx_int__INTC_CORTEXM0P_PRIORITY 3u
#define tty_rx_int__INTC_CORTEXM4_ASSIGNED 1
#define tty_rx_int__INTC_CORTEXM4_PRIORITY 7u
#define tty_rx_int__INTC_NUMBER 46u
#define tty_rx_int_INTC_CORTEXM0P_ASSIGNED 1
#define tty_rx_int_INTC_CORTEXM0P_MUX 8u
#define tty_rx_int_INTC_CORTEXM0P_PRIORITY 3u
#define tty_rx_int_INTC_CORTEXM4_ASSIGNED 1
#define tty_rx_int_INTC_CORTEXM4_PRIORITY 7u
#define tty_rx_int_INTC_NUMBER 46u

/* Button1_Int */
#define Button1_Int__INTC_CORTEXM4_ASSIGNED 1
#define Button1_Int__INTC_CORTEXM4_PRIORITY 7u
#define Button1_Int__INTC_NUMBER 122u
#define Button1_Int_INTC_CORTEXM4_ASSIGNED 1
#define Button1_Int_INTC_CORTEXM4_PRIORITY 7u
#define Button1_Int_INTC_NUMBER 122u

/* Button2_Int */
#define Button2_Int__INTC_CORTEXM4_ASSIGNED 1
#define Button2_Int__INTC_CORTEXM4_PRIORITY 7u
#define Button2_Int__INTC_NUMBER 123u
#define Button2_Int_INTC_CORTEXM4_ASSIGNED 1
#define Button2_Int_INTC_CORTEXM4_PRIORITY 7u
#define Button2_Int_INTC_NUMBER 123u

/* Button3_Int */
#define Button3_Int__INTC_CORTEXM4_ASSIGNED 1
#define Button3_Int__INTC_CORTEXM4_PRIORITY 7u
#define Button3_Int__INTC_NUMBER 124u
#define Button3_Int_INTC_CORTEXM4_ASSIGNED 1
#define Button3_Int_INTC_CORTEXM4_PRIORITY 7u
#define Button3_Int_INTC_NUMBER 124u

/* Button4_Int */
#define Button4_Int__INTC_CORTEXM4_ASSIGNED 1
#define Button4_Int__INTC_CORTEXM4_PRIORITY 7u
#define Button4_Int__INTC_NUMBER 125u
#define Button4_Int_INTC_CORTEXM4_ASSIGNED 1
#define Button4_Int_INTC_CORTEXM4_PRIORITY 7u
#define Button4_Int_INTC_NUMBER 125u

/* Button5_Int */
#define Button5_Int__INTC_CORTEXM4_ASSIGNED 1
#define Button5_Int__INTC_CORTEXM4_PRIORITY 7u
#define Button5_Int__INTC_NUMBER 126u
#define Button5_Int_INTC_CORTEXM4_ASSIGNED 1
#define Button5_Int_INTC_CORTEXM4_PRIORITY 7u
#define Button5_Int_INTC_NUMBER 126u

/* I2C_SCB_IRQ */
#define I2C_SCB_IRQ__INTC_CORTEXM4_ASSIGNED 1
#define I2C_SCB_IRQ__INTC_CORTEXM4_PRIORITY 7u
#define I2C_SCB_IRQ__INTC_NUMBER 47u
#define I2C_SCB_IRQ_INTC_CORTEXM4_ASSIGNED 1
#define I2C_SCB_IRQ_INTC_CORTEXM4_PRIORITY 7u
#define I2C_SCB_IRQ_INTC_NUMBER 47u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
